# Generated by Django 2.1.3 on 2018-11-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181120_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp_models',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
