# Generated by Django 2.1.3 on 2018-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181121_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp_models',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
